[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend="setuptools.build_meta"

[pytest]
log_cli = true
log_cli_level = "DEBUG"

[tool.pytest.ini_options]
markers = [
    "skip_instrument: Skip instrument tests if they are not available.",
    "skip_dataserver: Skip dataserver tests on live datasever."
]
filterwarnings = [
    "ignore:.*pkg_resources.*:DeprecationWarning"
]

[tool.isort]
profile = "black"
skip_gitignore = true
py_version = 310