[metadata]
name = qwip
version = 23.02.0
author = Larry Chen
author_email = larrychen@berkeley.edu
description = Quantum Workflows in Python
long_description = file: README.md
long_description_content_type = text/markdown

[options]
package_dir = 
    = src
packages = find:
install_requires = 
    attrs
    cattrs
    loguru
    matplotlib
    mysqlclient
    notifiers
    numpy
    pandas
    pendulum
    plotly
    qutip
    ruamel.yaml
    rustworkx
    scikit-learn
    scipy
    sqlalchemy
python_requires = >= 3.10

[options.packages.find]
where = src

[options.extras_require]
dev =
    black
    isort
    mkdocs-material
    mkdocstrings[python]
    mkdocs-git-revision-date-localized-plugin
    mkdocs-git-authors-plugin
    pytest
    ruff
    typer
slack = 
    fastapi
    gunicorn
    httpx
    respx
    uvicorn[standard]