site_name: QWiP
site_url: https://qnl-internal.berkeley.edu/QWiP
site_dir: site/QWiP
repo_name: qnl/QWiP
repo_url: https://github.com/qnl/QWiP
edit_uri: edit/main/docs/pages/
docs_dir: pages
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ../examples/docs
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
theme:
  name: material
  custom_dir: ./overrides
  font:
    text: Roboto
    code: Fira Code, Inconsolata
  palette:
    - scheme: berkeley-light
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    edit: material/file-edit-outline
    logo: material/home
    repo: fontawesome/brands/github
    view: material/file-eye-outline
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.indexes
watch:
  - ../src/qwip
  - ../examples/docs
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            paths: ../src/qwip
            show_source: true
          import:
            - https://docs.python.org/3/objects.inv
  - git-authors:
      enabled: true
  - git-revision-date-localized:
      type: date
extra_css:
  - assets/stylesheets/palette.css
  - assets/stylesheets/layout.css
  - assets/stylesheets/termynal.css
extra_javascript:
  - assets/js/termynal.js
  - assets/js/setup.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
validation:
  absolute_links: relative_to_docs
nav:
  - QWiP:
      - index.md
  - User Guide:
      - user-guide/index.md
      - Configuration Management:
          - user-guide/configuration/configuration.md
          - user-guide/configuration/first-steps.md
      - Sequencer:
          - user-guide/sequences/index.md
          - user-guide/sequences/waveforms.md
          - user-guide/sequences/timelines.md
          - user-guide/sequences/sequences.md
      - user-guide/workflow.md
  - Developer Guide:
      - developer-guide/index.md
      - developer-guide/roadmap.md
      - Guidelines:
          - developer-guide/guidelines/all-things-git.md
          - developer-guide/guidelines/coding-guidelines.md
          - developer-guide/guidelines/testing.md
          - developer-guide/guidelines/documentation.md
      - developer-guide/attrs.md
  - API Reference:
      - api/qwip/index.md
      - qwip:
          - qwip: api/qwip/index.md
          - qwip.defaults: api/qwip/defaults.md
          - qwip.flatdict: api/qwip/flatdict.md
          - qwip.settings: api/qwip/settings.md
          - qwip.testing: api/qwip/testing.md
          - qwip.typing: api/qwip/typing.md
          - qwip.utils: api/qwip/utils.md
      - qwip.analysis:
          - qwip.analysis: api/qwip/analysis/index.md
          - qwip.analysis.fitting: api/qwip/analysis/fitting.md
          - qwip.analysis.frequency: api/qwip/analysis/frequency.md
      - qwip.attrs:
          - qwip.attrs: api/qwip/attrs/index.md
          - qwip.attrs.schema: api/qwip/attrs/schema.md
          - qwip.attrs.serialization: api/qwip/attrs/serialization.md
          - qwip.attrs.validation: api/qwip/attrs/validation.md
      - qwip.backends:
          - qwip.backends: api/qwip/backends/index.md
          - qwip.backends.alazar: api/qwip/backends/alazar.md
          - qwip.backends.backend: api/qwip/backends/backend.md
          - qwip.backends.qtrl: api/qwip/backends/qtrl.md
          - qwip.backends.qubic: api/qwip/backends/qubic.md
          - qwip.backends.qutip: api/qwip/backends/qutip.md
          - qwip.backends.software: api/qwip/backends/software.md
          - qwip.backends.tektronix: api/qwip/backends/tektronix.md
          - qwip.backends.vna: api/qwip/backends/vna.md
      - qwip.calibration:
          - qwip.calibration: api/qwip/calibration/index.md
          - qwip.calibration.calibration: api/qwip/calibration/calibration.md
          - qwip.calibration.readout: api/qwip/calibration/readout.md
      - qwip.config:
          - qwip.config: api/qwip/config/index.md
          - qwip.config.interface: api/qwip/config/interface.md
          - qwip.config.models: api/qwip/config/models.md
          - qwip.config.schema: api/qwip/config/schema.md
          - qwip.config.static: api/qwip/config/static.md
      - qwip.data:
          - qwip.data: api/qwip/data/index.md
          - qwip.data.datastore: api/qwip/data/datastore.md
          - qwip.data.filesystem: api/qwip/data/filesystem.md
          - qwip.data.models: api/qwip/data/models.md
          - qwip.data.serializers: api/qwip/data/serializers.md
          - qwip.data.storage: api/qwip/data/storage.md
      - qwip.database:
          - qwip.database: api/qwip/database/index.md
          - qwip.database.database: api/qwip/database/database.md
          - qwip.database.dolt: api/qwip/database/dolt.md
          - qwip.database.metadata: api/qwip/database/metadata.md
          - qwip.database.utils: api/qwip/database/utils.md
      - qwip.instruments:
          - qwip.instruments: api/qwip/instruments/index.md
          - qwip.instruments.instrument_server: api/qwip/instruments/instrument_server.md
          - qwip.instruments.ltc2704: api/qwip/instruments/ltc2704.md
      - qwip.instruments.alazar:
          - qwip.instruments.alazar: api/qwip/instruments/alazar/index.md
          - qwip.instruments.alazar.alazar: api/qwip/instruments/alazar/alazar.md
          - qwip.instruments.alazar.atsapi: api/qwip/instruments/alazar/atsapi.md
      - qwip.processing:
          - qwip.processing: api/qwip/processing/index.md
          - qwip.processing.data_processor: api/qwip/processing/data_processor.md
          - qwip.processing.processors: api/qwip/processing/processors.md
      - qwip.qpu:
          - qwip.qpu: api/qwip/qpu/index.md
          - qwip.qpu.qpu: api/qwip/qpu/qpu.md
          - qwip.qpu.systems: api/qwip/qpu/systems.md
      - qwip.sequencer:
          - qwip.sequencer: api/qwip/sequencer/index.md
          - qwip.sequencer.compilation: api/qwip/sequencer/compilation.md
          - qwip.sequencer.elements: api/qwip/sequencer/elements.md
          - qwip.sequencer.instructions: api/qwip/sequencer/instructions.md
          - qwip.sequencer.phase_tracker: api/qwip/sequencer/phase_tracker.md
          - qwip.sequencer.sequence: api/qwip/sequencer/sequence.md
          - qwip.sequencer.timeline: api/qwip/sequencer/timeline.md
          - qwip.sequencer.utils: api/qwip/sequencer/utils.md
          - qwip.sequencer.waveform: api/qwip/sequencer/waveform.md
      - qwip.visualization:
          - qwip.visualization: api/qwip/visualization/index.md
          - qwip.visualization.dataframe: api/qwip/visualization/dataframe.md
          - qwip.visualization.readout: api/qwip/visualization/readout.md
          - qwip.visualization.utils: api/qwip/visualization/utils.md
      - qwip_dataserver:
          - qwip_dataserver: api/qwip_dataserver/index.md
          - qwip_dataserver.server: api/qwip_dataserver/server.md
          - qwip_dataserver.settings: api/qwip_dataserver/settings.md
  - Changelog: CHANGELOG.md
